fullname = "saba tavadze"

print(fullname)
print(fullname)
print(fullname)
print(fullname)
print(fullname)
print(fullname)
print(fullname)
print(fullname)
print(fullname)
print(fullname)
print(fullname)
print(fullname)
print(fullname)
print(fullname)
print(fullname)
print(fullname)
print(fullname)
print(fullname)
print(fullname)
print(fullname)